# offset of formal parameters with respect to ebp

.equ	p1, 8
.equ	p2, 12
.equ	p3, 16
.equ	p4, 20
.equ	p5, 24
.equ	p6, 28
.equ 	p7, 32
.equ	p8, 36
.equ	p9, 40
.equ	p10, 44
.equ	p11, 48
.equ	p12, 52
.equ	p13, 56
.equ	p14, 60
.equ	p15, 64


#offset of local variable with respect to ebp
.equ	loc1, -4
.equ	loc2, -8
.equ	loc3, -12
.equ	loc4, -16
.equ	loc5, -20
.equ	loc6, -24
.equ	loc7, -28
.equ	loc8, -32
.equ	loc9, -36
.equ	loc10, -40
.equ	loc11, -44
.equ	loc12, -48
.equ	loc13, -52
.equ	loc14, -56
.equ	loc15, -60
